//DropDown
export const FETCH_DEPARTMENTS = "FETCH_DEPARTMENTS";
export const FETCH_DEPARTMENTS_SUCCESS = "FETCH_DEPARTMENTS_SUCCESS";

//Employee information Posting
export const POSTING_EMPLOYEE_INFORMATION = "POSTING_EMPLOYEE_INFORMATION";
export const UPDATING_EMPLOYEE_INFORMATION = "UPDATING_EMPLOYEE_INFORMATION";
export const POSTING_EMPLOYEE_INFORMATION_SUCCESS = "POSTING_EMPLOYEE_INFORMATION_SUCCESS";
export const POSTING_EMPLOYEE_INFORMATION_FAILED = "POSTING_EMPLOYEE_INFORMATION_FAILED";



//Designation 

export const FETCH_DESIGNATION = "FETCH_DESIGNATION";
export const FETCH_DESIGNATION_SUCCESS = "FETCH_DESIGNATION_SUCCESS";

//EmployeeList 
export const FETCH_EMPLOYEELIST = "FETCH_EMPLOYEELIST";
export const FETCH_EMPLOYEELIST_SUCCESS = "FETCH_EMPLOYEELIST_SUCCESS";


//Salarycomponent

export const FETCH_SALARYCOMPONENT_SUCCESS = "FETCH_SALARYCOMPONENT_SUCCESS";




